name: Generate Release Notes
'on':
  push:
    tags:
      - v*
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v5
        with:
          version: '${{ github.ref_name }}'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
